[package]
name = "banque"
version = "0.1.0"
authors = ["Mihawka <mihawka@execaution.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
